### ISSUE TITLE
Unable to parse time returned from API call

### ISSUE THREAD

**Issue by bobmorley** [Apicurio/apicurio-registry-client-sdk-go#9]
Attempting to use generated client and `ArtifactsApi.CreateArtifact` fails attempting to parse the timestamps in the response. The artifact is was created, but if I attempt `MetadataApi.GetArtifactMetaData` on that artifact I get similar error.

`parsing time "\"2022-02-14T21:31:10+0000\"" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse "+0000\`

**Comment by craicoverflow** [comment]
Thanks for reporting this issue Bob! I'll take a look. Note that this SDK is still unstable and has not been released yet. It's fine to play around with but I don't recommend adding it to your applications just yet!

**Comment by craicoverflow** [comment]
As of #11 this should be fixed - with the caveat that timestamp fields on your structs will be a string, not a `time.Time` object.
